routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function() {
    $authors = \App\Models\Author::select('name')->get()->pluck('name');
    return view('home', compact('authors'));
});

Route::resource('authors', 'AuthorsController');
Route::resource('books', 'BooksController');

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    const ALREADY_EXISTS = 'Book already exists.';
    const CREATED_SUCCESSFULLY = 'Book created successfully.';
    const UPDATED_SUCCESSFULLY = 'Book updated successfully.';
    const DELETED_SUCCESSFULLY = 'Book deleted successfully.';
    const NOT_FOUND = 'Book not found.';

    /**
     * Mass-assignable attributes.
     *
     * @var array
     */
    protected $fillable = [
        'author_id',
        'title',
    ];

    /**
     * Author of the book.
     */
    public function author()
    {
        return $this->belongsTo(Author::class);
    }
}

app/Http/Controllers/Api/BooksController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Author;
use App\Models\Book;
use App\Repositories\BookRepository;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class BooksController extends Controller
{
    private $books;

    /**
     * Initialize instance with dependencies.
     */
    public function __construct(BookRepository $books)
    {
        $this->books = $books;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = $this->books->with([ 'author', ])->all();
        return $books;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $status = Response::HTTP_METHOD_NOT_ALLOWED;
        return response()
            ->json([ 'error' => Response::$statusTexts[$status] ], $status);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request
            ->validate([
                'title'     => 'required',
                'author'    => 'required',
            ]);

        // find or create author
        $author = Author::firstOrCreate(
            [ 'name'    => $data['author'], ],
            [ 'name'    => $data['author'], ]
        );

        // create book
        try {
            $book = $this->books
                 ->create([
                     'title'        => $data['title'],
                     'author_id'    => $author->id,
                 ]);
        } catch (QueryException $ex) {
            $error = $ex->getMessage();

            // unique constraint error -- TODO: consider using an error handler
            if ($ex->getCode() == 23505) {
                $error = Book::ALREADY_EXISTS;
            }

            return response()
                ->json(compact('error'), Response::HTTP_BAD_REQUEST);
        } catch (Exception $ex) {
            // TODO: log error

            return response()
                ->json([ 'error' => $ex->getMessage(), ], Response::HTTP_INTERNAL_SERVER_ERROR);
        }

        return $book;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $status = Response::HTTP_METHOD_NOT_ALLOWED;
        return response()
            ->json([ 'error' => Response::$statusTexts[$status] ], $status);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $status = Response::HTTP_METHOD_NOT_ALLOWED;
        return response()
            ->json([ 'error' => Response::$statusTexts[$status] ], $status);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $status = Response::HTTP_METHOD_NOT_ALLOWED;
        return response()
            ->json([ 'error' => Response::$statusTexts[$status] ], $status);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $status = Response::HTTP_METHOD_NOT_ALLOWED;
        return response()
            ->json([ 'error' => Response::$statusTexts[$status] ], $status);
    }

    /**
     * Export books in the specified format.
     *
     * This method relies on the fact that the Book transformer sets the
     * author's name in the `author` property.
     *
     * @see App\Transformers\BookTransformer
     * @param  string $format { csv, xml }
     * @return \Illuminate\Http\Response
     */
    public function export($format)
    {
        if (!in_array($format, [ 'csv', 'xml', ])) {
            $status = Response::HTTP_METHOD_NOT_ALLOWED;
            return response()
                ->json([ 'error' => Response::$statusTexts[$status] ], $status);
        }

        $books = $this->books->with([ 'author', ])->all();
        $fields = config('app.exportFields');

        // remove field if set to 0
        foreach ($fields as $f) {
            if (!request()->query($f, FALSE)) {
                unset($fields[array_search($f, $fields)]);
            }
        }

        // set default fields if empty
        if (count($fields) == 0) {
            $fields = config('app.exportFields');
        }

        // remove not exportable fields from model collection
        $records = array_map(function($author) use ($fields) {
            foreach ($author as $prop => $val) {
                foreach (array_keys($author) as $k) {
                    if (!in_array($k, $fields)) {
                        unset($author[$k]);
                    }
                }

                return $author;
            }
        }, $books['data']);

        if ($format == 'csv') {
            return response()->csv($records);
        } else {
            return response()
                ->xml(
                    $records,
                    Response::HTTP_OK,
                    [
                        'template' => '<books></books>',
                        'rowName' => 'book',
                    ]
                );
        }
    }
}

app/Http/Controllers/BooksController.php
<?php

namespace App\Http\Controllers;

use App\Models\Author;
use App\Models\Book;
use Illuminate\Http\Request;

class BooksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::with('author:id,name')->get();
        return view('books/index', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return $this->showForm(NULL, 'store');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'author_id'  => 'required',
            'title'  => 'required',
        ]);

        try {
            $book = Book::create($data);
            $request->session()->flash('status', Book::CREATED_SUCCESSFULLY);
        } catch (QueryException $ex) {
            $request->session()->flash('error', "Error ocurred: {$ex->getMessage()}");
            return back()->withInput();
        }

        return redirect()->route('books.show', [ 'id' => $book->id ]);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $book = Book::with('author')->find($id);

        if ($book == NULL) {
            return redirect()->route('books.index')
                             ->with('error', Book::NOT_FOUND);
        }

        return view('books/show', compact('book'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return $this->showForm($id, 'update');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request
            ->validate([
                'author_id' => 'required',
                'title'     => 'required',
            ]);
        $book = Book::find($id);

        if ($book == NULL) {
            return redirect()->route('books.index')
                             ->with('error', Book::NOT_FOUND);
        }

        try {
            $book->update($data);
            $request->session()->flash('status', Book::UPDATED_SUCCESSFULLY);
        } catch (QueryException $ex) {
            $request->session()->flash('error', "Error ocurred: {$ex->getMessage()}");
            return back()->withInput();
        }

        return redirect()->route('books.show', [ 'id' => $book->id ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = Book::find($id);

        if ($book == NULL) {
            return redirect()->route('books.index')
                             ->with('error', Book::NOT_FOUND);
        }

        try {
            $book->delete();
        } catch (QueryException $ex) {
            return redirect()->route('books.index')
                ->with('error', "There was an error deleting the book: {$ex->getMessage()}");
        }

        return redirect()->route('books.index')
                         ->with('status', Book::DELETED_SUCCESSFULLY);
    }

    /**
     * Display Book form to user.
     *
     * @param  int $id
     * @param  string $action
     * @return \Illuminate\Http\Response
     */
    private function showForm($id = NULL, $action)
    {
        $author_id = (int) request()->query('author_id');

        if ($id != NULL) {
            $book = Book::find($id);

            if ($book == NULL) {
                return redirect()->route('books.index')
                                 ->with('error', Book::NOT_FOUND);
            }
            $author_id = $book->author_id;
        } else {
            $book = new Book;
        }

        $authors = Author::select([ 'id', 'name' ])->get();

        return view('books/form', compact('book', 'action', 'authors', 'author_id'));
    }
}

resources/views/books/destroy-confirm.blade.php
@section('modals')
@modal([ 'modalId' => 'destroyBookModal' ])
    @slot('title') Caution @endslot

    <p>
        Are you sure you want to delete the book?
    </p>

    @slot('actions')
        @destroy([ 'url' => route('books.destroy', compact('id')) ])
        @enddestroy
    @endslot
@endmodal
@endsection

resources/views/books/form.blade.php
@extends('layouts/app')

@section('content')
<h2>
    {{ $action == 'update' ? 'Edit' : 'Add' }} Book
</h2>

@if ($action == 'update')
<div class="text-right">
    <a class="btn btn-primary" href="{{ route('books.show', ['id' => $book->id]) }}">
        Show
    </a>
</div>
@endif

<form action="{{ route("books.{$action}", ['id' => $book->id]) }}" method="POST">
    @csrf
    @if ($action != 'store')
        @method('PUT')
    @endif

    <div class="form-row">
        <div class="col form-group">
            <label for="author_id">
                Author
            </label>
            <select class="form-control" name="author_id" id="author_id" required>
                <option disabled selected>Select author</option>
            @foreach ($authors as $author)
                <option
                    value="{{ $author->id }}"
                    @if ($author->id == $author_id)
                    selected
                    @endif
                >{{ $author->name }}</option>
            @endforeach
            </select>
        </div>

        <div class="col form-group">
            <label for="title">
                Name
            </label>
            <input name="title" id="title" class="form-control" value="{{ $book->title }}" required>
        </div>
    </div>

    @submit([ 'action' => ($action == 'update' ? 'Update' : 'Create') ])
    @endsubmit
</form>
@endsection

resources/views/books/index.blade.php
@extends('layouts/app')

@section('content')
<h2>Books</h2>

<div class="text-right mb-3">
    <a href="{{ route('books.create') }}" class="btn btn-primary">
        Add a book
    </a>
</div>

<table class="table table-hover table-responsive-md">
    <thead class="thead-dark">
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Author</th>
            <th colspan="3">Actions</th>
        </tr>
    </thead>

    <tbody>
    @foreach ($books as $book)
        <tr>
            <td>{{ $book->id }}</td>
            <td>{{ $book->title }}</td>
            <td>
                <a href="{{ route('authors.show', ['id' => $book->author_id]) }}">
                    {{ $book->author->name }}
                </a>
            </td>
            <td>
                <a href="{{ route('books.show', ['id' => $book->id]) }}">
                    Show
                </a>
            </td>
            <td>
                <a href="{{ route('books.edit', ['id' => $book->id]) }}">
                    Edit
                </a>
            </td>
            <td>
                <button
                    type="button"
                    class="btn btn-danger destroy-book"
                    data-id="{{ $book->id }}"
                    data-toggle="modal"
                    data-target="#destroyBookModal"
                >
                    Delete
                </button>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
@endsection

@section('js')
<script type="text/javascript">
window.addEventListener('DOMContentLoaded', function(ev) {
    // this is hackish, but it gets the job done
    $('.destroy-book').click(function(ev) {
        var id = $(ev.target).data('id');
        $('#destroyBookModal form')
            .prop('action', "{{ route('books.index') }}/" + id);
    });
});
</script>
@endsection

@include('books/destroy-confirm', [ 'id' => NULL ])

resources/views/books/show.blade.php
@extends('layouts/app')

@section('content')
<h2>{{ $book->title }}</h2>
<h3 class="text-secondary">
    by <a href="{{ route('authors.show', ['id' => $book->author_id]) }}">
        {{ $book->author->name }}
    </a>
</h3>

<div class="text-right">
    <a class="btn btn-primary" href="{{ route('authors.edit', ['id' => $book->author_id]) }}">
        Edit author
    </a>
    <a class="btn btn-primary" href="{{ route('books.edit', ['id' => $book->id]) }}">
        Edit
    </a>
    <button
        type="button"
        class="btn btn-danger"
        data-toggle="modal"
        data-target="#destroyBookModal"
    >
        Delete
    </button>
</div>

<div>
    Lorem aliquid incidunt eaque qui laboriosam! Et optio provident dicta minima tempore at hic maxime Repellendus laudantium laudantium tenetur et quo Ratione quam porro animi quas eaque? Non necessitatibus officia?
</div>
@endsection

@include('books/destroy-confirm', [ 'id' => $book->id ])