routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function() {
    $authors = \App\Models\Author::select('name')->get()->pluck('name');
    return view('home', compact('authors'));
});

Route::resource('authors', 'AuthorsController');
Route::resource('books', 'BooksController');

app/Models/Author.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
    const CREATED_SUCCESSFULLY = 'Author created successfully.';
    const UPDATED_SUCCESSFULLY = 'Author updated successfully.';
    const DELETED_SUCCESSFULLY = 'Author deleted successfully.';
    const NOT_FOUND = 'Author not found.';

    /**
     * Mass-assignable attributes.
     *
     * @var array
     */
    protected $fillable = [
        'name',
    ];

    /**
     * Books written by the author.
     */
    public function books()
    {
        return $this->hasMany(Book::class);
    }
}

app/Http/Controllers/AuthorsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Author;
use Illuminate\Http\Request;
use Illuminate\Database\QueryException;

class AuthorsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $authors = Author::all();
        return view('authors/index', compact('authors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return $this->showForm(NULL, 'store');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'name'  => 'required|unique:authors',
        ]);

        try {
            $author = Author::create($data);
            $request->session()->flash('status', Author::CREATED_SUCCESSFULLY);
        } catch (QueryException $ex) {
            $request->session()->flash('error', "Error ocurred: {$ex->getMessage()}");
            return back()->withInput();
        }

        return redirect()->route('authors.show', [ 'id' => $author->id ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $author = Author::with('books')->find($id);

        if ($author == NULL) {
            return redirect()->route('authors.index')
                             ->with('error', Author::NOT_FOUND);
        }

        return view('authors/show', compact('author'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return $this->showForm($id, 'update');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request
            ->validate([
                'name'  => 'required|unique:authors',
            ]);
        $author = Author::find($id);

        if ($author == NULL) {
            return redirect()->route('authors.index')
                             ->with('error', Author::NOT_FOUND);
        }

        try {
            $author->update($data);
            $request->session()->flash('status', Author::UPDATED_SUCCESSFULLY);
        } catch (QueryException $ex) {
            $request->session()->flash('error', "Error ocurred: {$ex->getMessage()}");
            return back()->withInput();
        }

        return redirect()->route('authors.show', [ 'id' => $author->id ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $author = Author::find($id);

        if ($author == NULL) {
            return redirect()->route('authors.index')
                             ->with('error', Author::NOT_FOUND);
        }

        try {
            $author->delete();
        } catch (QueryException $ex) {
            return redirect()->route('authors.index')
                ->with('error', "There was an error deleting the author: {$ex->getMessage()}");
        }

        return redirect()->route('authors.index')
                         ->with('status', Author::DELETED_SUCCESSFULLY);
    }

    /**
     * Display Author form to user.
     *
     * @param  int $id
     * @param  string $action
     * @return \Illuminate\Http\Response
     */
    private function showForm($id = NULL, $action)
    {
        if ($id != NULL) {
            $author = Author::find($id);

            if ($author == NULL) {
                return redirect()->route('authors.index')
                                 ->with('error', Author::NOT_FOUND);
            }
        } else {
            $author = new Author;
        }

        return view('authors/form', compact('author', 'action'));
    }
}

resources/views/authors/destroy-confirm.blade.php
@section('modals')
@modal([ 'modalId' => 'destroyAuthorModal' ])
    @slot('title') Caution @endslot
    @slot('actions')
        @destroy([ 'url' => route('authors.destroy', compact('id')) ])
        @enddestroy
    @endslot

    <p>
        Are you sure you want to delete the author? This will
        <strong class="text-danger">
            delete all books associated to it
        </strong>.
    </p>
@endmodal
@endsection

resources/views/authors/form.blade.php
@extends('layouts/app')

@section('content')
<h2>
    {{ $action == 'update' ? 'Edit' : 'Add' }} Author
</h2>

@if ($action == 'update')
<div class="text-right">
    <a class="btn btn-primary" href="{{ route('authors.show', ['id' => $author->id]) }}">
        Show
    </a>
</div>
@endif

<form action="{{ route("authors.{$action}", ['id' => $author->id]) }}" method="POST">
    @csrf
    @if ($action != 'store')
        @method('PUT')
    @endif

    <div class="form-group">
        <label for="name">
            Name
        </label>
        <input
            name="name"
            id="name"
            class="form-control"
            value="{{ $author->name }}"
            required
        >
    </div>

    @submit([ 'action' => ($action == 'update' ? 'Update' : 'Create') ])
    @endsubmit
</form>
@endsection

resources/views/authors/index.blade.php
@extends('layouts/app')

@section('content')
<h2>Authors</h2>

<div class="text-right mb-3">
    <a href="{{ url('/authors/create') }}" class="btn btn-primary">
        Add an author
    </a>
</div>

<table class="table table-hover table-responsive-md">
    <thead class="thead-dark">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th colspan="3">Actions</th>
        </tr>
    </thead>

    <tbody>
    @foreach ($authors as $author)
        <tr>
            <td>{{ $author->id }}</td>
            <td>{{ $author->name }}</td>
            <td>
                <a href="{{ route('authors.show', ['id' => $author->id]) }}">
                    Show
                </a>
            </td>
            <td>
                <a href="{{ route('authors.edit', ['id' => $author->id]) }}">
                    Edit
                </a>
            </td>
            <td>
                <button
                    type="button"
                    class="btn btn-danger destroy-author"
                    data-id="{{ $author->id }}"
                    data-toggle="modal"
                    data-target="#destroyAuthorModal"
                >
                    Delete
                </button>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
@endsection

@section('js')
<script type="text/javascript">
window.addEventListener('DOMContentLoaded', function(ev) {
    // this is hackish, but it gets the job done
    $('.destroy-author').click(function(ev) {
        var id = $(ev.target).data('id');
        $('#destroyAuthorModal form')
            .prop('action', "{{ route('authors.index') }}/" + id);
    });
});
</script>
@endsection

@include('authors/destroy-confirm', [ 'id' => NULL ])

resources/views/authors/show.blade.php
@extends('layouts/app')

@section('content')
<h2>{{ $author->name }}</h2>

<div class="text-right">
    <a class="btn btn-primary" href="{{ route('books.create', ['author_id' => $author->id]) }}">
        Add book
    </a>
    <a class="btn btn-primary" href="{{ route('authors.edit', ['id' => $author->id]) }}">
        Edit
    </a>
    <button
        type="button"
        class="btn btn-danger"
        data-toggle="modal"
        data-target="#destroyAuthorModal"
    >
        Delete
    </button>
</div>

<div>
    Lorem aliquid incidunt eaque qui laboriosam! Et optio provident dicta minima tempore at hic maxime Repellendus laudantium laudantium tenetur et quo Ratione quam porro animi quas eaque? Non necessitatibus officia?
</div>

<hr>

<h3>Books</h3>

<section class="author-books row justify-content-around">
@forelse ($author->books as $book)
    <article class="card col-12 col-md-4  m-2">
        <div class="card-body">
            <h4 class="card-title">{{ $book->title }}</h4>

            <p class="card-text">Adipisicing sapiente ipsum maiores enim quibusdam atque debitis. Placeat et sunt voluptates quia quaerat commodi? Delectus fugiat architecto vero nam odio excepturi, amet. Sit aliquam libero autem quas voluptatem eum</p>

            <a class="btn btn-primary" href="{{ route('books.show', ['id' => $book->id]) }}">
                See
            </a>
        </div>
    </article>
@empty
    <p class="col">This author has no books</p>
@endforelse
</section>
@endsection

@include('authors/destroy-confirm', [ 'id' => $author->id ])